<?php
// Incluir tus archivos de conexión
require_once 'Connect.php';
require_once 'Conexion.php';

function respaldarBaseDatosCompleto()
{
    try {
        // Usar las variables globales de Connect.php directamente
        global $host, $user, $pass, $db;

        // Crear conexión PDO directamente
        $pdo = new PDO("mysql:host=$host;dbname=$db;charset=utf8", $user, $pass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        // Nombre del archivo con identificador único
        $fecha = date('Y-m-d_H-i-s');
        $filename = "respaldo_completo_sifcao_{$fecha}.sql";

        // Configurar headers para descarga directa
        header('Content-Type: application/sql');
        header('Content-Disposition: attachment; filename="' . $filename . '"');

        // Contenido del respaldo
        $backup_content = "-- MySQL COMPLETE Backup Generated by PHP\n";
        $backup_content .= "-- Database: {$db}\n";
        $backup_content .= "-- Host: {$host}\n";
        $backup_content .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
        $backup_content .= "-- Includes: TABLES, VIEWS, PROCEDURES, FUNCTIONS, TRIGGERS\n";
        $backup_content .= "-- File: {$filename}\n";
        $backup_content .= "-- --------------------------------------------------\n\n";

        // 1. RESPALDAR TABLAS (estructura y datos)
        $backup_content .= "-- ==========================================\n";
        $backup_content .= "-- TABLES\n";
        $backup_content .= "-- ==========================================\n\n";

        $stmt = $pdo->query("SHOW TABLES");
        $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);

        if (empty($tables)) {
            $backup_content .= "-- No se encontraron tablas en la base de datos\n\n";
        } else {
            foreach ($tables as $table) {
                $backup_content .= "--\n-- Table structure for table `{$table}`\n--\n\n";

                $create_stmt = $pdo->query("SHOW CREATE TABLE `{$table}`");
                $create_table = $create_stmt->fetch(PDO::FETCH_ASSOC);

                $backup_content .= "DROP TABLE IF EXISTS `{$table}`;\n";
                $backup_content .= $create_table['Create Table'] . ";\n\n";

                $backup_content .= "--\n-- Dumping data for table `{$table}`\n--\n\n";

                $data_stmt = $pdo->query("SELECT * FROM `{$table}`");
                $rows = $data_stmt->fetchAll(PDO::FETCH_ASSOC);

                if (!empty($rows)) {
                    foreach ($rows as $row) {
                        $columns = array_map(function ($value) use ($pdo) {
                            if ($value === null) {
                                return 'NULL';
                            }
                            return $pdo->quote($value);
                        }, $row);

                        $backup_content .= "INSERT INTO `{$table}` VALUES (" . implode(', ', $columns) . ");\n";
                    }
                    $backup_content .= "\n";
                }
            }
        }

        // 2. RESPALDAR VISTAS (VIEWS)
        $backup_content .= "-- ==========================================\n";
        $backup_content .= "-- VIEWS\n";
        $backup_content .= "-- ==========================================\n\n";

        $views_stmt = $pdo->query("
            SELECT TABLE_NAME 
            FROM INFORMATION_SCHEMA.VIEWS 
            WHERE TABLE_SCHEMA = '$db'
        ");
        $views = $views_stmt->fetchAll(PDO::FETCH_COLUMN);

        if (empty($views)) {
            $backup_content .= "-- No se encontraron vistas en la base de datos\n\n";
        } else {
            foreach ($views as $view) {
                $backup_content .= "--\n-- View structure for view `{$view}`\n--\n\n";

                $create_view_stmt = $pdo->query("SHOW CREATE VIEW `{$view}`");
                $create_view = $create_view_stmt->fetch(PDO::FETCH_ASSOC);

                $backup_content .= "DROP VIEW IF EXISTS `{$view}`;\n";
                $backup_content .= $create_view['Create View'] . ";\n\n";
            }
        }

        // 3. RESPALDAR PROCEDIMIENTOS ALMACENADOS (STORED PROCEDURES)
        $backup_content .= "-- ==========================================\n";
        $backup_content .= "-- STORED PROCEDURES\n";
        $backup_content .= "-- ==========================================\n\n";

        $procedures_stmt = $pdo->query("
            SELECT ROUTINE_NAME, ROUTINE_DEFINITION
            FROM INFORMATION_SCHEMA.ROUTINES 
            WHERE ROUTINE_SCHEMA = '$db' 
            AND ROUTINE_TYPE = 'PROCEDURE'
        ");
        $procedures = $procedures_stmt->fetchAll(PDO::FETCH_ASSOC);

        if (empty($procedures)) {
            $backup_content .= "-- No se encontraron procedimientos almacenados\n\n";
        } else {
            foreach ($procedures as $procedure) {
                $backup_content .= "--\n-- Stored Procedure: `{$procedure['ROUTINE_NAME']}`\n--\n\n";

                $create_proc_stmt = $pdo->query("SHOW CREATE PROCEDURE `{$procedure['ROUTINE_NAME']}`");
                $create_procedure = $create_proc_stmt->fetch(PDO::FETCH_ASSOC);

                $backup_content .= "DROP PROCEDURE IF EXISTS `{$procedure['ROUTINE_NAME']}`;\n";
                $backup_content .= "DELIMITER //\n";
                $backup_content .= $create_procedure['Create Procedure'] . "//\n";
                $backup_content .= "DELIMITER ;\n\n";
            }
        }

        // 4. RESPALDAR FUNCIONES (STORED FUNCTIONS)
        $backup_content .= "-- ==========================================\n";
        $backup_content .= "-- STORED FUNCTIONS\n";
        $backup_content .= "-- ==========================================\n\n";

        $functions_stmt = $pdo->query("
            SELECT ROUTINE_NAME
            FROM INFORMATION_SCHEMA.ROUTINES 
            WHERE ROUTINE_SCHEMA = '$db' 
            AND ROUTINE_TYPE = 'FUNCTION'
        ");
        $functions = $functions_stmt->fetchAll(PDO::FETCH_COLUMN);

        if (empty($functions)) {
            $backup_content .= "-- No se encontraron funciones almacenadas\n\n";
        } else {
            foreach ($functions as $function) {
                $backup_content .= "--\n-- Stored Function: `{$function}`\n--\n\n";

                $create_func_stmt = $pdo->query("SHOW CREATE FUNCTION `{$function}`");
                $create_function = $create_func_stmt->fetch(PDO::FETCH_ASSOC);

                $backup_content .= "DROP FUNCTION IF EXISTS `{$function}`;\n";
                $backup_content .= "DELIMITER //\n";
                $backup_content .= $create_function['Create Function'] . "//\n";
                $backup_content .= "DELIMITER ;\n\n";
            }
        }

        // 5. RESPALDAR TRIGGERS
        $backup_content .= "-- ==========================================\n";
        $backup_content .= "-- TRIGGERS\n";
        $backup_content .= "-- ==========================================\n\n";

        $triggers_stmt = $pdo->query("
            SELECT TRIGGER_NAME, EVENT_OBJECT_TABLE
            FROM INFORMATION_SCHEMA.TRIGGERS 
            WHERE TRIGGER_SCHEMA = '$db'
        ");
        $triggers = $triggers_stmt->fetchAll(PDO::FETCH_ASSOC);

        if (empty($triggers)) {
            $backup_content .= "-- No se encontraron triggers en la base de datos\n\n";
        } else {
            foreach ($triggers as $trigger) {
                $backup_content .= "--\n-- Trigger: `{$trigger['TRIGGER_NAME']}` on table `{$trigger['EVENT_OBJECT_TABLE']}`\n--\n\n";

                $create_trigger_stmt = $pdo->query("SHOW CREATE TRIGGER `{$trigger['TRIGGER_NAME']}`");
                $create_trigger = $create_trigger_stmt->fetch(PDO::FETCH_ASSOC);

                $backup_content .= "DROP TRIGGER IF EXISTS `{$trigger['TRIGGER_NAME']}`;\n";
                $backup_content .= "DELIMITER //\n";
                $backup_content .= $create_trigger['SQL Original Statement'] . "//\n";
                $backup_content .= "DELIMITER ;\n\n";
            }
        }

        // Resumen final
        $backup_content .= "-- ==========================================\n";
        $backup_content .= "-- BACKUP SUMMARY\n";
        $backup_content .= "-- ==========================================\n";
        $backup_content .= "-- Tables: " . count($tables) . "\n";
        $backup_content .= "-- Views: " . count($views) . "\n";
        $backup_content .= "-- Stored Procedures: " . count($procedures) . "\n";
        $backup_content .= "-- Stored Functions: " . count($functions) . "\n";
        $backup_content .= "-- Triggers: " . count($triggers) . "\n";
        $backup_content .= "-- Backup completed at: " . date('Y-m-d H:i:s') . "\n";

        // Enviar contenido directamente al navegador
        echo $backup_content;
        exit;
    } catch (PDOException $e) {
        // Si hay error, mostrar como JSON
        header('Content-Type: application/json');
        echo json_encode([
            'success' => false,
            'message' => 'Error de conexión a la base de datos: ' . $e->getMessage()
        ]);
    } catch (Exception $e) {
        header('Content-Type: application/json');
        echo json_encode([
            'success' => false,
            'message' => $e->getMessage()
        ]);
    }
}

// Ejecutar el respaldo completo
respaldarBaseDatosCompleto();